# This is a basic workflow to help you get started with Actions

name: Windows CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Installs Gem Modules
    - name: Install Gem Modules
      run: gem install ocra rubyzip
      
    # Build Project
    - name: Build Project
      run: mkdir dist && ocra --gemfile Gemfile --no-dep-run run.rb --output dist/modparse.exe
      
    # Upload Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ModParse-win32
        path: D:\a\ModParse\ModParse\bin
